approve_by_comment: true
approve_regex: '[Aa]pprove'
reject_regex: '[Rr]eject'
reject_value: -1
reset_on_push: false
author_approval: ignored
reviewers:
    -
        required: 1
        members:
            - kinbiko
            - burtybob
        conditions:
            branches:
                - master  # only need to approve if merging to master
